<a href="https://colab.research.google.com/github/Seongjin1225/AI_SCHOOL_9/blob/main/ML%26DL/11%EC%9B%94%2028%EC%9D%BC/11%EC%9B%94_28%EC%9D%BC_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 미분의 프로그램적 구현

In [ ]:
# 일변수 함수의 수치미분 코드 구현
# 입력으로 함수를 받아서 미분을 수행하는 함수를 하나 구현해 보아요!
# 우리 파이썬은 일급함수를 지원
# 함수의 인자로 다른 함수를 받을 수 있다.
def numeric_derivative(f,x):

    # 입력인자 f는 미분하려는 함수
    # 입력인자 x는 미분값을 알려고하는 입력값

    delta_x = 1e-4

    # 중앙차분을 이용한 미분을 코드로 표현해보아요
    result = (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)
    return result

# 정상적으로 값을 계산하는지 확인!
def my_func(x):
    return x ** 2

# 함수 f(x) = x ** 2의 미분계수 f'(5)를 구해보아요
result = numeric_derivative(my_func,5)
print(result)

9.999999999976694


In [ ]:
# 다변수 함수의 수치미분 코드를 만들어보아요!
import numpy as np

def numeric_derivative(f,x):

    # f : 미분하려는 함수
    # x : 모든 변수를 포함하는 ndarray

    delta_x = 1e-4
    derivative_x = np.zeros_like(x)  # zeros_like -> 어떤 특정 array와 같은 사이즈, 크기의 zeros array 구함

    it = np.nditer(x, flags=['multi_index'])
    while not it.finished:
        idx = it.multi_index  # 현재의 index를 추출 => tuple형태로 리턴.

        tmp = x[idx]    # 현재 index의 값을 일단 잠시 보존해야해요!
                        # 밑에서 이 값을 변경해서 중앙차분 값을 계산해야 해요!
                        # 그런데 우리 편미분해야해요. 다음 변수 편미분할때
                        # 원래값으로 복원해야 편미분이 정상적으로 진행되기 때문에
                        # 이값을 잠시 보관했다가 원상태로 복구해야 해요!

        x[idx] = tmp + delta_x
        fx_plus_delta_x = f(x)  # f(x + delta_x)

        x[idx] = tmp - delta_x
        fx_minus_delta_x = f(x) # f(x - delta_x)

        derivative_x[idx] = (fx_plus_delta_x - fx_minus_delta_x) / (2 * delta_x)

        x[idx] = tmp

        it.iternext()

    return derivative_x

def my_func(x):
    return x ** 2

# f'(3.0)을 구해보아요!
result = numeric_derivative(my_func, np.array([3.0]))
result

array([6.])

In [ ]:
# 2변수 함수를 다시 만들어보아요
def my_func(input_data):
    x = input_data[0]
    y = input_data[1]

    return 2*x + 3*x*y + np.power(y,3)  # np.power(m,n) --> m의 n 제곱 해주는 함수

result = numeric_derivative(my_func, np.array([1.0, 2.0]))
result

array([ 8.        , 15.00000001])

In [ ]:
# 4변수 함수에 대해 수치미분 해보기
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# f'(1.0, 2.0, 3.0, 4.0)의 값은?

def my_func(input_data):
    w = input_data[0,0]
    x = input_data[0,1]
    y = input_data[1,0]
    z = input_data[1,1]
    return w*x + x*y*z + 3*w + z*np.power(y,2)

data = np.array([[1.0, 2.0],
                 [3.0, 4.0]])
result = numeric_derivative(my_func, data)
result

array([[ 5., 13.],
       [32., 15.]])